#!/bin/bash
## Set some parameters
MOVIES_DIR=/export/Movies/

## Check if sqlite3 is installed
s=$(which sqlite3 > /dev/null;echo $?)
if [ $s -eq 0 ]; then
	echo "Already have sqlite3 installed"
else
	echo "You don't have sqlite3 installed, I'll install it"
	apt-get update && apt-get install sqlite3 -qy
fi

## If database not present, initialise it
if [ ! -e data.db ];
then
	## Create movies table
	create="create table MOVIES(id INTEGER PRIMARY KEY, tt TEXT UNIQUE, title TEXT, year NUMERIC, plot TEXT, create_dt TEXT);"
	sqlite3 data.db "${create}"

	## Create TV table
	##
	##

	## Create run log
	create="create table LOG(id INTEGER PRIMARY KEY, type TEXT, run_dt TEXT);"
	sqlite3 data.db
fi

## Scan for new movies
## Iterate over movies directory
for m in $MOVIES_DIR/*/*.nfo
do
	## Get imdb id
	tt=$(grep -oPm1 "(?<=<id>)[^<]+" <<< more "${m}")

	tt_db=`sqlite3 data.db "select * from MOVIES where tt='${tt}';"`
	if [ -z "$tt_db" ];
	then
		echo "Found new movie $tt, creating entry"

		## Get data from omdbapi
		xml=`curl -s http://www.omdbapi.com/?i="${tt}"&plot=short&r=json`

		## Parse out title, plot, year
		title=$(echo "${xml}" |grep -Po '"Title":.*?[^\\]",')
		title=${title:9:${#title}-11}
		echo $title

		plot=$(echo "${xml}" |grep -Po '"Plot":.*?[^\\]",')
		plot=${plot:8:${#plot}-10}
		echo "${plot}"

		year=$(echo "${xml}" |grep -Po '"Year":.*?[^\\]",')
		year=${year:8:${#year}-10}
		echo "${year}"

		## Insert into database
		insert="insert or ignore into MOVIES (tt, title, year, plot, create_dt) values ('${tt}', '${title//\'/''}', '${year}','${plot//\'/''}', CURRENT_TIMESTAMP)"
		#echo $insert
		sqlite3 data.db "${insert}"
	fi
done

## Prepare a list of updates
LAST_RUN=`sqlite3 data.db "SELECT MAX(strftime('%s', run_dt)) from LOG;"`

if [ -f updates.html ];
then
	rm updates.html
fi

echo "Last run $LAST_RUN"
UPDATES=`sqlite3 data.db "SELECT tt FROM MOVIES WHERE strftime('%s', create_dt) > '${LAST_RUN}';"`
if [ ! -z "$UPDATES" ];
then
	echo "<html>" >> updates.html
	echo "<body>" >> updates.html
	for row in $UPDATES;
	do

		title=`sqlite3 data.db "select title from MOVIES where tt = '${row}';"`
		year=`sqlite3 data.db "select year from MOVIES where tt = '${row}';"`
		echo "<a href=\"www.imdb.com/title/${row}\">${title} (${year})</a>" >> updates.html
		plot=`sqlite3 data.db "select plot from MOVIES where tt = '${row}';"`
		echo "${plot} <br />" >> updates.html
	done
	echo "</body>" >> updates.html
	echo "</html>" >> updates.html
	mpack -s Movies updates.html najmead@gmail.com

else
	echo "No updates"
fi
## LOG timestamp of run
#log="insert into LOG(type, run_dt) values ('movies', CURRENT_TIMESTAMP);"
#sqlite3 data.db "${log}"

